// Estilos compartidos por los formularios "Nuevo ..." de cada módulo.
// Los pseudo-estados (focus, hover) viven en admin.css bajo las
// clases cmf-input / cmf-btn-primary / cmf-btn-secondary.

export const formStyles = {
  formTitle: {
    fontFamily: '"Playfair Display", Georgia, serif',
    fontWeight: 400,
    fontSize: '1.2rem',
    color: '#1a1510',
    marginBottom: '20px',
  },
  formGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginBottom: '24px',
  },
  field: { display: 'flex', flexDirection: 'column', gap: '5px' },
  label: {
    fontSize: '0.68rem',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    color: '#888',
  },
  input: {
    padding: '10px 12px',
    border: '1px solid #ddd',
    borderRadius: '2px',
    fontSize: '0.88rem',
    outline: 'none',
    fontFamily: '"Inter", system-ui, sans-serif',
    color: '#1a1510',
    background: '#fff',
  },
  select: {
    padding: '10px 12px',
    border: '1px solid #ddd',
    borderRadius: '2px',
    fontSize: '0.88rem',
    outline: 'none',
    fontFamily: '"Inter", system-ui, sans-serif',
    color: '#1a1510',
    background: '#fff',
  },
  textarea: {
    padding: '10px 12px',
    border: '1px solid #ddd',
    borderRadius: '2px',
    fontSize: '0.88rem',
    outline: 'none',
    fontFamily: '"Inter", system-ui, sans-serif',
    resize: 'vertical',
    color: '#1a1510',
  },
  check: {
    fontSize: '0.82rem',
    color: '#555',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    cursor: 'pointer',
    marginTop: '6px',
  },
  error: { color: '#9b2525', fontSize: '0.8rem', marginBottom: '16px' },
  actions: { display: 'flex', gap: '12px' },
  btnSave: {
    background: '#9b2525',
    color: '#fff',
    border: 'none',
    borderRadius: '2px',
    padding: '11px 24px',
    fontSize: '0.78rem',
    letterSpacing: '0.08em',
    cursor: 'pointer',
  },
  btnCancel: {
    background: 'none',
    border: '1px solid #ccc',
    borderRadius: '2px',
    padding: '11px 24px',
    fontSize: '0.78rem',
    cursor: 'pointer',
    color: '#666',
  },
};
